# Generated by Django 4.1.3 on 2024-04-01 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersDetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('job', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('kebele', models.CharField(max_length=100)),
                ('raw_image_url', models.URLField()),
                ('cam_image_url', models.URLField()),
                ('prediction', models.JSONField(default=list)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersDetail.usersdetail')),
            ],
        ),
    ]
