# Generated by Django 4.2.10 on 2024-04-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsdetail',
            name='cam_image_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientsdetail',
            name='gender',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='patientsdetail',
            name='raw_image_url',
            field=models.CharField(max_length=100),
        ),
    ]
