# Generated by Django 4.2.10 on 2024-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0002_alter_patientsdetail_cam_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsdetail',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='patientsdetail',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patientsdetail',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='patientsdetail',
            name='cam_image_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientsdetail',
            name='job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientsdetail',
            name='kebele',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientsdetail',
            name='raw_image_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientsdetail',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patientsdetail',
            name='zone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
