# Generated by Django 4.2.16 on 2024-09-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0003_rename_doctor_patientsdetail_doctor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitals_name', models.CharField(max_length=200)),
                ('hospitals_street', models.CharField(max_length=200)),
                ('hospitals_city', models.CharField(max_length=200)),
                ('hospitals_woreda', models.CharField(max_length=200)),
                ('hospitals_zone', models.CharField(max_length=200)),
                ('hospitals_region', models.CharField(max_length=200)),
                ('hospitals_country', models.CharField(max_length=200)),
                ('hospitals_id', models.IntegerField()),
            ],
        ),
    ]
