# Generated by Django 4.2.16 on 2024-09-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0004_hospitalsdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsdetail',
            old_name='cam_image_url',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='hospitalsdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patientsdetail',
            name='raw_image_url',
        ),
        migrations.AlterField(
            model_name='hospitalsdetail',
            name='hospitals_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patientsdetail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
