# Generated by Django 4.2.16 on 2024-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0006_remove_patientsdetail_prediction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsdetail',
            name='image_url',
        ),
        migrations.AddField(
            model_name='patientsdetail',
            name='left_eye_image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patientsdetail',
            name='right_eye_image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
