# Generated by Django 4.2.16 on 2024-10-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0008_alter_patientsdetail_left_eye_prediction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hospitalsDetail',
        ),
    ]
