# Generated by Django 4.2.16 on 2024-10-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientsDetail', '0010_patientsdetail_record_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientsImageAndPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_eye_image_url', models.CharField(blank=True, max_length=200)),
                ('right_eye_image_url', models.CharField(blank=True, max_length=200)),
                ('left_eye_prediction', models.JSONField(null=True)),
                ('right_eye_prediction', models.JSONField(null=True)),
                ('record_date', models.DateField(default=django.utils.timezone.now)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientsDetail.patientsdetail')),
            ],
        ),
    ]
