# Generated by Django 4.2.16 on 2024-10-07 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0011_patientsimageandprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicianDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(default=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('disease', models.TextField(default='', max_length=200, null=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientsDetail.patientsimageandprediction')),
            ],
        ),
    ]
