# Generated by Django 4.2.16 on 2024-10-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0012_physiciandecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsimageandprediction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
