# Generated by Django 4.2.16 on 2024-10-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0015_patientsdetail_hospital_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsdetail',
            old_name='hospital_id',
            new_name='health_institution',
        ),
    ]
