# Generated by Django 4.2.16 on 2024-10-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsDetail', '0018_rename_left_eye_image_url_patientsimageandprediction_image_prediction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsimageandprediction',
            old_name='limage_url',
            new_name='image_url',
        ),
    ]
