# Generated by Django 4.1.3 on 2024-04-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('kebele', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('passport', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('BLOCKED', 'Blocked')], max_length=10)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User')], max_length=110)),
            ],
        ),
    ]
