# Generated by Django 4.2.11 on 2024-04-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='passport',
            field=models.URLField(),
        ),
    ]
