# Generated by Django 4.2.11 on 2024-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0002_alter_usersdetail_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='passport',
            field=models.CharField(max_length=100),
        ),
    ]
