# Generated by Django 4.2.10 on 2024-04-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0006_alter_usersdetail_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='role',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('BLOCKED', 'Blocked')], max_length=110, null=True),
        ),
    ]
