# Generated by Django 4.2.10 on 2024-04-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0007_alter_usersdetail_gender_alter_usersdetail_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdetail',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='usersdetail',
            name='lastname',
        ),
    ]
