# Generated by Django 4.2.10 on 2024-04-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0008_remove_usersdetail_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('USER', 'User')], max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('BLOCKED', 'Blocked')], max_length=12, null=True),
        ),
    ]
