# Generated by Django 4.2.16 on 2024-10-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0009_alter_usersdetail_role_alter_usersdetail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdetail',
            old_name='organization',
            new_name='hospital',
        ),
    ]
