# Generated by Django 4.2.16 on 2024-10-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0010_rename_organization_usersdetail_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
