# Generated by Django 4.2.16 on 2024-10-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0011_healthyinstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='health_institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usersDetail.healthyinstitution'),
            preserve_default=False,
        ),
    ]
