# Generated by Django 4.2.16 on 2024-10-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersDetail', '0012_usersdetail_health_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthyinstitution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
